tools:
  alpha_agent:
    level: 3
    type: llm_call_agent
    available_tools:
      - execute_command
      - human_in_loop
      - load_skill
      - judge_agent
      - file_read
      - file_write
      - file_move
      - dir_list
      - dir_create
      - final_output
      - image_read
      - parse_document
      - web_search
      - google_scholar_search
      - arxiv_search
      - crawl_page
      - file_download
      - create_image
      - reference_list
      - reference_add
      - reference_delete
      - sub_agent
    max_turns: 100
    model_type: openai/qwen-plus
    prompts:
      agent_responsibility: |
        你的职责是一个通用的 AI 助手, 是cowork的主要智能体。
      agent_workflow: |
        详细分析用户的意图(如果不清晰，请通过提供选项的方式和用户交互明确需求），并根据意图编排使用你的工具完成任务。

    name: "alpha_agent"
    description: "你的职责是一个通用的 AI 助手, 是 cowork的主要智能体"
    parameters:
      type: "object"
      properties:
        task_id:
          type: "string"
          description: "任务的唯一ID。"
        task_input:
          type: "string"
          description: "用户写作需求的初始指令"
      required: ["task_id", "task_input"]
  

  sub_agent:
    level: 3
    type: llm_call_agent
    available_tools:
      - execute_command
      - human_in_loop
      - load_skill
      - judge_agent
      - file_read
      - file_write
      - file_move
      - dir_list
      - dir_create
      - final_output
      - image_read
      - parse_document
      - web_search
      - google_scholar_search
      - arxiv_search
      - crawl_page
      - file_download
      - create_image
      - reference_list
      - reference_add
      - reference_delete
    max_turns: 100
    model_type: claude-3-7-sonnet-20250219
    prompts:
      agent_responsibility: |
        你的职责是一个通用的 AI 助手, 是由上级调用的子智能体，完成一些比较独立的工作。
      agent_workflow: |
        详细分析用户的意图(如果不清晰，请通过提供选项的方式和用户交互明确需求），并根据意图编排使用你的工具完成任务。

    name: "sub_agent"
    description: "你的职责是一个通用的 AI 助手, 是由上级调用的子智能体，完成一些比较独立的工作。"
    parameters:
      type: "object"
      properties:
        task_id:
          type: "string"
          description: "任务的唯一ID。"
        task_input:
          type: "string"
          description: "用户写作需求的初始指令"
      required: ["task_id", "task_input"]

         

